project/cart/views.py
from flask import Blueprint, render_template, redirect, url_for, request, session, flash
from project.models import Product, Order, Cart
from project.admin.forms import AddOrderForm
from project import db

carts = Blueprint("carts", __name__)


def cart_function():
    products = []
    total_price = 0
    index = 0
    session["total_quantity"] = 0

    if "cart" in session:
        for item in session["cart"]:
            product = Product.query.filter_by(id=item["id"]).first()

            quantity = int(item["quantity"])
            total = quantity * product.price
            total_price += total
            session["total_quantity"] += quantity

            products.append({"id": product.id, "name": product.name, "price": product.price, "image": product.image,
                             "quantity": quantity, "total": total, "index": index})
            index += 1

    total_plus_shipping = total_price + 10
    return products, total_price, total_plus_shipping, session["total_quantity"]


@carts.route("/cart", methods=["POST", "GET"])
def cart():
    products, total_price, total_plus_shipping, total_quantity = cart_function()
    return render_template("cart.html", products=products, total_price=total_price,
                           total_plus_shipping=total_plus_shipping, total_quantity=total_quantity)


@carts.route("/add_to_cart", methods=["POST", "GET"])
def add_to_cart():
    if "cart" not in session:
        session["cart"] = []

    session["cart"].append({"id": request.form.get("product_id"), "quantity": request.form.get("quantity")})
    session.modified = True
    return redirect(url_for("carts.cart"))


@carts.route("/remove_from_cart/<index>")
def remove_from_cart(index):
    del session["cart"][int(index)]
    session.modified = True
    return redirect(url_for("carts.cart"))


@carts.route("/checkout", methods=["POST", "GET"])
def checkout():
    form = AddOrderForm()
    products, total_price, total_plus_shipping, total_quantity = cart_function()
    if form.validate_on_submit():
        order = Order(first_name=form.first_name.data,
                      last_name=form.last_name.data,
                      email=form.email.data,
                      country=form.country.data,
                      city=form.city.data,
                      zip_code=form.zip_code.data,
                      address=form.address.data,
                      card_number=form.card_number.data,
                      security_number=form.security_number.data,
                      card_date=form.card_date.data)

        for product in products:
            order_item = Cart(quantity=product["quantity"], product_id=product["id"])
            order.items.append(order_item)

            product = Product.query.filter_by(id=product["id"]).update({"stock": Product.stock - product["quantity"]})

        db.session.add(order)
        db.session.commit()

        session["cart"] = []
        session.modified = True
        flash("Thank you for your order!")
        return redirect(url_for("carts.cart"))
    return render_template("checkout.html", form=form, total_price=total_price,
                           total_plus_shipping=total_plus_shipping, total_quantity=total_quantity)

project/core/views.py
from flask import render_template, Blueprint, request, session
from project.models import Product
from project.core.forms import FilterForm

core = Blueprint("core", __name__)


@core.route("/", methods=["GET", "POST"])
def home():
    page = request.args.get("page", 1, type=int)
    product = Product.query.order_by(Product.id.desc()).paginate(page=page, per_page=8)
    try:
        session["total_quantity"]
    except KeyError:
        session["total_quantity"] = 0
    return render_template("home.html", product=product, page=page, total_quantity=session["total_quantity"])


def product(product_type):
    form = FilterForm()
    products = Product.query.filter_by(category=f"{product_type[:-1]}").all()
    filter_result = request.form.get("subcategory_filter")
    filter_product = []
    for product in products:
        if product.subcategory == filter_result:
            filter_product.append(product)
        elif filter_result == "all products":
            filter_product.append(product)
    return render_template("products.html", form=form, filter_product=filter_product,
                           filter_result=filter_result, products=products, total_quantity=session["total_quantity"])


@core.route("/bracelets", methods=["GET", "POST"])
def bracelets():
    return product("bracelets")


@core.route("/earrings", methods=["GET", "POST"])
def earrings():
    return product("earrings")


@core.route("/necklaces", methods=["GET", "POST"])
def necklaces():
    return product("necklaces")


@core.route("/rings", methods=["GET", "POST"])
def rings():
    return product("rings")


@core.route("/product<int:product_id>", methods=["GET", "POST"])
def about_product(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template("about_product.html", product=product, total_quantity=session["total_quantity"])

project/users/views.py
from project import db
from flask import Blueprint, flash, redirect, render_template, url_for, session
from project.users.forms import RegistrationForm, LoginForm
from project.models import User, Product, Wishlist
from flask_login import logout_user, login_user, login_required, current_user

users = Blueprint("users", __name__)


@users.route("/registration", methods=["GET", "POST"])
def registration():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(first_name=form.first_name.data, last_name=form.last_name.data, email=form.email.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in!")
        return redirect(url_for("users.login"))
    return render_template("registration.html", form=form, total_quantity=session["total_quantity"])


@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            return redirect(url_for("core.home", user=user))
    return render_template("login.html", form=form, total_quantity=session["total_quantity"])


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("core.home"))


@users.route("/account")
@login_required
def account():
    wishlist = Wishlist.query.filter_by(user_id=current_user.id).all()
    products = []

    for wish in wishlist:
        product = Product.query.filter_by(id=wish.product_id).first()
        products.append(product)
    return render_template("account.html", wishlist=wishlist, products=products, total_quantity=session["total_quantity"])


@users.route("/<product_id>/add-to-wishlist")
@login_required
def add_to_wishlist(product_id):
    wishlist = Wishlist(user_id=current_user.id, product_id=product_id)
    db.session.add(wishlist)
    db.session.commit()
    return redirect(url_for("users.account"))


@users.route("/<product_id>/remove-from-wishlist")
@login_required
def remove_from_wishlist(product_id):
    wishlist = Wishlist.query.filter_by(product_id=product_id).first()
    db.session.delete(wishlist)
    db.session.commit()
    return redirect(url_for("users.account"))

project/templates/about_product.html
{% extends "index.html" %}
{% block content %}


<div class="card mb-3" id="about-product">
  <div class="row g-0">
    <div class="col-md-4">
      <img class="card-img-top" src=/static/images/{{ product.image }} alt="{{product.name}} image" style="height: 450px; width:450px;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 id="name">{{product.name.upper()}}</h4>
        <h6 id="price">{{product.price}} €</h6>
        <h5 id="category">{{product.category.upper()}} / {{product.subcategory.upper()}}</h5>

        {% if product.stock > 0 %}
            <form method ="POST" action="{{url_for('carts.add_to_cart')}}" id="about-form">

                <input type="hidden" value="{{product.id}}" name="product_id">

                <label for="quantity">QUANTITY: </label>
                <input type="number" min="1" max="{{product.stock}}" step="1" name="quantity" id="quantity" value="1">

                <br><button class="btn" type="submit" style="border-radius:0;">ADD TO CART </button>

                {% if current_user.is_authenticated %}
                    <a href="{{url_for('users.add_to_wishlist', product_id=product.id)}}" class="btn" id="wish-a">ADD TO WISHLIST</a>
                {% endif %}
            </form>
        {% else %}
            <h5 style="font-weight: 650; color: grey;">Out of stock</h5>
        {% endif %}

        <h5 id="description">DESCRIPTION:</h5>
        <h5 id="description2">{{product.description.capitalize()}}</h5><br>

        <h6>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">
            <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/></svg>
            Free shipping over 50 €</h6>
        <h6>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box" viewBox="0 0 16 16">
            <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/></svg>
            Free and easy returns</h6>
      </div>
    </div>
  </div>
</div>

{% endblock %}

project/templates/account.html
{% extends "index.html" %}
{% block content %}

<div>
  <img class="card-img" src='static/background/account.jpg' id="bracelet-img" style="height: 100%;">
  <div id="account-info">
    <h6>MY ACCOUNT</h6>
    <p>{{current_user.first_name}} {{current_user.last_name}}</p>
    <p>{{current_user.email}}</p>
    </div>
</div>

<h3 id="wishlist-title">{{current_user.first_name.upper()}}'S WISHLIST</h3>
{% if not products %}
  <h3 id="empty-wishlist">WISHLIST IS EMPTY!</h3>
  <a id="empty-wishlist-a" href="{{ url_for('core.home') }}">CONTINUE SHOPPING</a>
{% endif %}

<div class="row row-cols-2 row-cols-md-4 g-3" id="cards-home">
  {% for product in products %}
      <div class="col">
        <div class="card h-100" id="card-home" style="transform: scale(1.0);">
          <a href="{{url_for('core.about_product', product_id=product.id)}}"><img class="card-img-top" src=/static/images/{{ product.image }} alt="Card image cap" ></a>
          <div class="card-body">
            <h5 class="card-title"><a href="{{url_for('core.about_product', product_id=product.id)}}">{{product.name.upper()}}</a></h5>
            <p class="card-text">{{product.price}} €</p>
            <a href="{{url_for('users.remove_from_wishlist', product_id=product.id)}}" class="btn" id="list-remove">REMOVE</a>
          </div>
        </div>
      </div>
  {% endfor %}
</div>

{% endblock %}

project/templates/cart.html
{% extends "index.html" %}
{% block content %}

<h3 id="bag-title">SHOPPING BAG</h3>
{% if total_quantity == 0 %}
	<h6 id="empty-bag">YOUR BAG IS EMPTY!</h6>
	<a id="empty-bag-a" href="{{ url_for('core.home') }}">CONTINUE SHOPPING</a>
{% else %}
	<table id="cart-table">
		<tr>
			<th></th>
			<th>PRODUCT</th>
			<th>PRICE</th>
			<th>QUANTITY</th>
			<th>TOTAL</th>
			<th></th>
		</tr>

		{% for product in products %}
			<tr id="table-info">
				<td><img src=/static/images/{{product.image}} alt="image" style="width: 100px; height: 100px;"></td>
				<td>{{product.name.capitalize()}}</td>
				<td>{{product.price}} €</td>
				<td>{{product.quantity}}</td>
				<td>{{product.total}} €</td>
				<td><a href="{{url_for('carts.remove_from_cart', index=product.index)}}"><button id="cart-remove" type="button"> REMOVE </button></a></td>
			</tr>
		{% endfor %}
	</table>

	<div id="cart-summary">
		<h3 class="bold">CART SUMMARY</h3>
		<ul class="list-group">
			<li class="list-group-item">
				<p>{{total_quantity}} ITEMS: <strong class="pull-right">{{total_price}} €</strong></p>

				{% if total_price >= 50 %}
					<p>SHIPPING: <strong class="pull-right">0 €</strong></p>
				{% else %}
					<p>SHIPPING: <strong class="pull-right">10 €</strong></p>
				{% endif %}
			</li>

			{% if total_price >= 50 %}
				<li class="list-group-item" id="cart-total">
					<p>TOTAL: <strong class="pull-right">{{total_price}} €</strong></p>
				</li>
			{% else %}
				<li class="list-group-item" id="cart-total2">
					<p>TOTAl: <strong class="pull-right">{{total_plus_shipping}} €</strong></p>
				</li>
			{% endif %}
		</ul>
		<div class="panel-footer">
			<a href="{{url_for('carts.checkout')}}" class="btn">CHECKOUT</a>&nbsp;&nbsp;
			<a id="continue" href="{{url_for('core.home')}}" class="btn">CONTINUE SHOPPING</a>
		</div>
	</div>
{% endif %}

{% endblock %}

project/templates/checkout.html
{% extends "index.html" %}
{% block content %}

<h3 id="checkout-title">SHIPPING INFORMATION</h3>

<div class="row" id="checkout-row">
	<div class="col-6" id="info-group">
		<div class="panel panel-primary">
			<form method="POST" action="{{url_for('carts.checkout')}}">
				<div class="panel-body">
					<div class="row" id="personal-info">
						<div class="col-12">
							<h4 class="bold">PERSONAL INFORMATION</h4>
						</div>

						<div class="col-12" >
							<div class="form-group">
								{{form.hidden_tag()}}
								<label>Email</label><br>
								{{form.email(id="checkout-email")}}<br>
								{% for error in form.email.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<label>First name</label><br>
								{{form.first_name(id="checkout-first")}}<br>
								{% for error in form.first_name.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<label>Last name</label><br>
								{{form.last_name(id="checkout-last")}}<br>
								{% for error in form.last_name.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
					</div>
					<div class="row" id="address-info">
						<div class="col-12">
							<h4 class="bold">ADDRESS</h4>
						</div>
						<div class="col-6">
							<div class="form-group">
								<label>Address</label><br>
								{{form.address(id="checkout-address")}}<br>
								{% for error in form.address.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
							<div class="form-group">
								<label>City</label><br>
								{{form.city(id="checkout-city")}}<br>
								{% for error in form.city.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<label>Zip Code</label><br>
								{{form.zip_code(id="checkout-zip")}}<br>
								{% for error in form.zip_code.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
							<div class="form-group">
								<label>Country</label><br>
								{{form.country(id="checkout-country")}}<br>
								{% for error in form.country.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
					</div>
					<div class="row" id="payment-info">
						<div class="col-12">
							<h4 class="bold">PAYMENT</h4>
						</div>
						<div class="col-12">
							<div class="form-group">
								<label>Card number</label><br>
								{{form.card_number(id="checkout-card")}}<br>
								{% for error in form.card_number.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								{{form.security_number.label}}<br>
								{{form.security_number(id="checkout-cvv")}}<br>
								{% for error in form.security_number.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<label>Card date</label><br>
								{{form.card_date(id="checkout-date")}}<br>
								{% for error in form.card_date.errors %}
									<span style="color: #e50000;">{{ error }}</span><br>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer" id="panel2">
					<button type="submit" class="btn" id="order-btn">ORDER</button>&nbsp;&nbsp;
					<a id="return" href="{{url_for('carts.cart')}}" class="btn">RETURN TO CART</a>
				</div>
			</form>
		</div>
	</div>

	<div class="col-6" id="cart-details">
		<h4 class="bold">CART SUMMARY</h4>
		<ul class="list-group" id="cart-details2">
			<li class="list-group-item">
				<p>{{total_quantity}} ITEMS: <strong class="pull-right">{{total_price}} €</strong></p>
				{% if total_price >= 50 %}
					<p>SHIPPING: <strong class="pull-right">0 €</strong></p>
				{% else %}
					<p>SHIPPING: <strong class="pull-right">10 €</strong></p>
				{% endif %}
			</li>
			{% if total_price >= 50 %}
				<li class="list-group-item" id="cart-total">
					<p>TOTAL: <strong class="pull-right">{{total_price}} €</strong></p>
				</li>
			{% else %}
				<li class="list-group-item" id="cart-total2">
					<p>TOTAl: <strong class="pull-right">{{total_plus_shipping}} €</strong></p>
				</li>
			{% endif %}
		</ul>
	</div>
</div>

{% endblock %}

project/templates/index.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Caslon+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Stick+No+Bills:wght@600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="static/style.css" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="shortcut icon" href="static/favicon.png" type="image/png">
    <title>Jewelry Design</title>
</head>

<body class="d-flex flex-column min-vh-100">

    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand active" href="{{url_for('core.home')}}" id="store-name">JEWELRY DESIGN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <div class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if current_user.email == "admin@admin.com" %}
                            <a class="nav-item nav-link" href="{{url_for('admin.index')}}" id="nav-admin">ADMIN</a>
                        {% endif %}
                    </div>

                    <div class="navbar-nav me-auto mb-2 mb-lg-0" id="types">
                        <a class="nav-item nav-link" href="{{url_for('core.bracelets')}}" id="bracelets_link">BRACELETS</a>
                        <a class="nav-item nav-link" href="{{url_for('core.earrings')}}" id="earrings_link">EARRINGS</a>
                        <a class="nav-item nav-link" href="{{url_for('core.necklaces')}}" id="necklaces_link">NECKLACES</a>
                        <a class="nav-item nav-link" href="{{url_for('core.rings')}}" id="rings_link">RINGS</a>
                    </div>

                    <div class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <a class="nav-item nav-link" href="{{url_for('carts.cart')}}" id="nav-bag">BAG <span style="font-weight:bold;">{{total_quantity}}</span></a>
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{url_for('users.account')}}" id="nav-account">ACCOUNT</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}" id="nav-logout">LOG OUT</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{url_for('users.login')}}" id="nav-account2">ACCOUNT</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid" style="padding:0;">
        <div class="row">
            <div class="col">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
            </div>
        </div>
    </div>

    {% block content %}{% endblock %}

    <footer class="mt-auto" id="footer-basic">
         <div class="social">
             <a href="https://www.instagram.com/">
                 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                     <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/></svg>
             </a>
             <a href="https://twitter.com/">
                 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                     <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/></svg>
             </a>
             <a href="https://www.facebook.com/">
                 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                     <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/></svg>
             </a>
         </div>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="{{url_for('core.home')}}">Home</a></li>
            <li class="list-inline-item"><a href="#">About</a></li>
            <li class="list-inline-item"><a href="#">Contact</a></li>
            <li class="list-inline-item"><a href="#">Terms</a></li>
            <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
        </ul>
        <p class="copyright">Jewelry Design © 2021</p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>